### ISSUE TITLE
Get OP2 Running

### ISSUE THREAD

**Issue by NickWalker1** [Highly-Predictable-Calamity/PGAS-OP2-Common#1]
The scope of this ticket includes:

- [x] Running the default airfoil simulation code (done but wrong results)
- [ ] Ask Gihan why the airfoil simulation results are wrong
- [x] A wiki on how to easily recreate this (so we can all do it later)

**Comment by Nat-133** [comment]
Got it working exactly as described by using mesh size 600x800.
Higher resolutions give higher error, I assume when compared to the non-parallelised version. I think this is because higher resolution meshes mean more floating point operations and so greater chance for divergence between versions, but we might want to ask Gihan if that's correct.

**Comment by NickWalker1** [comment]
I'm still unable to do updates due to my laptop. @coolbruiser  can you, follow the guide to make sure it works? I'll do it also once my laptop is fixed :)

**Comment by ben-metz** [comment]
Guide works for getting OP2 set up!

**Comment by NickWalker1** [comment]
@janekjan can you create an MR so we can merge to main if all is good?

**Comment by janekjan** [comment]
Sure, there's no branch to merge here, docs is already in Notes/main, but I closed the issue as resolved
